### PR TITLE
lib: don't swallow user errors

### LINKED ISSUE #40: Swallows errors
For some reason errors gets swallowed and never see the light of day if thrown within an event from `mdns-js`.

```javascript
var mdns = require('mdns-js')
var browser = mdns.createBrowser('_tessel._tcp')

browser.once('ready', function () {
  browser.discover()
})

browser.on('update', function (c) {
  console.log('Silent death')
  throw new Error('test')
})
```

### PR DESCRIPTION
**Pull request by LinusU**
This fixes #40

### CODE REVIEW

**Comment by LinusU** [comment]
@kmpm Ping! :)

**Comment by LinusU** [comment]
@kmpm ping :)

**Comment by kmpm** [comment]
Thanks,
Sorry for being slow, to much other stuff.

**Comment by LinusU** [comment]
No problem, do you mind cutting a release on npm that we can depend on? Thanks

**Comment by kmpm** [comment]
Give me a couple of hours, have some more merges to do.
Den 3 sep 2015 5:19 em skrev "Linus Unnebäck" <notifications@github.com>:

**Comment by kmpm** [comment]
released

**Pull request merged**
